lvgl:
  pages:
    - id: main_page
      bg_opa: COVER
      bg_color: 0xffffff
      widgets:
        - obj:
            id: main_left_pane
            styles: clean_obj
            width: 460
            height: 522
            x: 9
            y: 9
            layout:
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: START
              flex_align_cross: SPACE_EVENLY
              flex_align_track: SPACE_AROUND

            widgets:
              - obj:
                  id: main_left_date_date
                  width: 460
                  height: 40
                  styles: clean_obj
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_BETWEEN
                  widgets:
                    - label:
                        id: main_left_date_weekday
                        text: "Aaaaaaa"
                        text_font: "roboto_32_bold"
                    - label:
                        id: main_left_date_day
                        text: "xx Xxxxxxx"
                        text_font: "roboto_32"
              - obj:
                  width: 460
                  height: 120
                  styles: clean_obj
                  id: main_left_date_time
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: CENTER
                    flex_align_cross: CENTER
                  widgets:
                    - label:
                        id: main_left_date_hour
                        text: "--"
                        text_font: "roboto_96_num_bold"
                    - label:
                        id: main_left_date_minute
                        text: ":--"
                        text_font: "roboto_96_num"

              - obj:
                  id: main_left_splitter1
                  width: 460
                  height: 2
                  bg_opa: COVER
                  bg_color: 0xd9d9d9
                  styles: clean_obj

              - label:
                  id: main_left_weather_logo_now
                  width: 130
                  height: 150
                  text: "\uf172"
                  text_font: "weather_xxl"

              - obj:
                  id: main_left_weather_data
                  height: 150
                  width: 200
                  bg_opa: TRANSP
                  styles: clean_obj
                  layout:
                    type: FLEX
                    flex_flow: COLUMN
                    flex_align_main: CENTER
                    flex_align_cross: CENTER
                    flex_align_track: CENTER
                  widgets:
                    - obj:
                        id: main_left_weather_temp
                        width: 155
                        height: 90
                        radius: 0
                        styles: clean_obj
                        layout:
                          type: FLEX
                          flex_flow: ROW
                          flex_align_main: CENTER
                        widgets:
                          - label:
                              id: main_left_weather_temp_now
                              text: "??"
                              height: 90
                              text_font: "roboto_80_num_bold"
                          - label:
                              id: main_left_weather_temp_txt
                              text: "\u00b0C"
                              text_font: "roboto_32"
                    - label:
                        id: main_left_weather_temp_feels
                        text: "Feels like: ??\u00b0C"
                        text_font: "roboto_16"
                    - label:
                        id: main_left_weather_temp_rain
                        text: "Rain: ??%"
                        text_font: "roboto_16"

              - obj:
                  id: main_left_weather_details
                  width: 110
                  height: 150
                  styles: clean_obj
                  layout:
                    type: FLEX
                    flex_flow: COLUMN
                    flex_align_main: SPACE_BETWEEN
                  widgets:
                    - obj:
                        id: main_left_weather_details_sunrise_cont
                        styles: clean_obj
                        width: SIZE_CONTENT
                        height: 38
                        layout:
                          type: FLEX
                          flex_flow: ROW
                          flex_align_main: START
                          flex_align_cross: CENTER
                        widgets:
                          - label:
                              id: main_left_weather_details_sunrise_logo
                              text: "\ue81a"
                              text_font: "icons_large"
                          - label:
                              id: main_left_weather_details_sunrise
                              text: "hh:mm"
                              text_font: "roboto_16"
                    - obj:
                        id: main_left_weather_details_sunset_cont
                        styles: clean_obj
                        width: SIZE_CONTENT
                        height: 38
                        layout:
                          type: FLEX
                          flex_flow: ROW
                          flex_align_main: START
                          flex_align_cross: CENTER
                        widgets:
                          - label:
                              id: main_left_weather_details_sunset_logo
                              text: "\ue1c6"
                              text_font: "icons_large"
                          - label:
                              id: main_left_weather_details_sunset
                              text: "HH:MM"
                              text_font: "roboto_16"
                    - obj:
                        id: main_left_weather_details_wind_cont
                        styles: clean_obj
                        bg_color: 0xffffff
                        bg_opa: COVER
                        width: SIZE_CONTENT
                        height: 38
                        layout:
                          type: FLEX
                          flex_flow: ROW
                          flex_align_main: START
                          flex_align_cross: CENTER
                        widgets:
                          - label:
                              id: main_left_weather_details_wind_logo
                              text: "\uefd8"
                              text_font: "icons_large"
                          - label:
                              id: main_left_weather_details_wind
                              text: "??km/h"
                              text_font: "roboto_16"

              - obj:
                  id: main_left_splitter_1
                  width: 460
                  height: 2
                  bg_opa: COVER
                  bg_color: 0xd9d9d9
                  styles: clean_obj

              - obj:
                  id: main_left_forecast
                  styles: clean_obj
                  width: 460
                  height: SIZE_CONTENT
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_EVENLY
                    flex_align_cross: START
                  widgets:
                    - obj:
                        id: main_left_forecast_4h
                        styles: clean_obj
                        layout:
                          type: FLEX
                          flex_flow: COLUMN
                          flex_align_main: START
                          flex_align_cross: CENTER
                        widgets:
                          - label:
                              id: main_left_forecast_4h_time
                              text: "hh:mm"
                              text_font: "roboto_24"
                          - label:
                              id: main_left_forecast_4h_icon
                              text: "\ue81a"
                              text_font: "icons_large"
                          - label:
                              id: main_left_forecast_4h_temp
                              text: "??\u00b0C / ??%"
                              text_font: "roboto_24"
                    - obj:
                        id: main_left_forecast_8h
                        styles: clean_obj
                        layout:
                          type: FLEX
                          flex_flow: COLUMN
                          flex_align_main: START
                          flex_align_cross: CENTER
                        widgets:
                          - label:
                              id: main_left_forecast_8h_time
                              text: "hh:mm"
                              text_font: "roboto_24"
                          - label:
                              id: main_left_forecast_8h_icon
                              text: "\ue81a"
                              text_font: "icons_large"
                          - label:
                              id: main_left_forecast_8h_temp
                              text_font: "roboto_24"
                              text: "??\u00b0C / ??%"
                    - obj:
                        id: main_left_forecast_12h
                        styles: clean_obj
                        layout:
                          type: FLEX
                          flex_flow: COLUMN
                          flex_align_main: START
                          flex_align_cross: CENTER
                        widgets:
                          - label:
                              id: main_left_forecast_12h_time
                              text: "hh:mm"
                              text_font: "roboto_24"
                          - label:
                              id: main_left_forecast_12h_icon
                              text: "\ue81a"
                              text_font: "icons_large"
                          - label:
                              id: main_left_forecast_12h_temp
                              text: "??\u00b0C / ??%"
                              text_font: "roboto_24"

        - obj:
            id: main_pane_splitter
            width: 4
            x: 478
            y: 9
            height: 522
            bg_opa: COVER
            bg_color: 0xd9d9d9
            styles: clean_obj

        - obj:
            id: main_right_pane
            styles: clean_obj
            x: 491
            y: 60
            width: 460
            height: 470
            layout:
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: SPACE_BETWEEN
              flex_align_cross: START
            bg_color: 0xffffff
            bg_opa: COVER
            widgets:
              - obj: !include
                  file: "snippets/rollers.yaml"
                  vars:
                    name: "dani"
                    label: "Dani"
                    ha_entity: "dani_rollers_cover_1"

              - obj: !include
                  file: "snippets/rollers.yaml"
                  vars:
                    name: "oli"
                    label: "Oli"
                    ha_entity: "oli_roller_cover_1"

              - obj: !include
                  file: "snippets/rollers.yaml"
                  vars:
                    name: "eltern"
                    label: "Eltern"
                    ha_entity: "eltern_rollers_cover_1"

              - obj: !include
                  file: "snippets/rollers.yaml"
                  vars:
                    name: "living_rol"
                    label: "Living L"
                    ha_entity: "living_large_rollers_cover_1"

              - obj: !include
                  file: "snippets/rollers.yaml"
                  vars:
                    name: "living_ros"
                    label: "Living S"
                    ha_entity: "living_small_roller_cover_1"

              - obj:
                  id: main_right_studio_night
                  styles: main_controls
                  layout:
                    type: FLEX
                    flex_flow: ROW_WRAP
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    flex_align_track: SPACE_BETWEEN
                  widgets:
                    - button:
                        id: main_controls_dach_rollers
                        state:
                          disabled: true
                        width: 130
                        height: 85
                        styles: clean_obj
                        focused:
                          styles: clean_obj
                        pressed:
                          styles: clean_obj
                        edited:
                          styles: clean_obj
                        on_click:
                          - homeassistant.action:
                              action: scene.turn_on
                              data:
                                entity_id: scene.dg_studio_night
                        widgets:
                          - label:
                              id: main_controls_dach_rollers_label
                              text: "\ue2a7"
                              text_font: "icons_xlarge"
                              align: center
                    - label:
                        text: "Dach Rollers"
                        styles: main_controls_label
                        long_mode: DOT

              - obj:
                  id: main_right_keller_light
                  styles: main_controls
                  layout:
                    type: FLEX
                    flex_flow: ROW_WRAP
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    flex_align_track: SPACE_BETWEEN
                  widgets:
                    - button:
                        id: main_controls_keller_light_long
                        state:
                          disabled: true
                        width: 130
                        height: 85
                        checkable: true
                        styles:
                          - main_controls_button
                        pressed:
                          styles:
                            - main_controls_button_pressed
                        focused:
                          styles:
                            - main_controls_button_focused
                        checked:
                          styles:
                            - main_controls_button_checked
                        widgets:
                          - label:
                              id: main_controls_keller_light_long_state
                              text: "\ue0f0"
                              text_font: "icons_xlarge"
                              align: center
                        on_click:
                          - homeassistant.action:
                              action: light.toggle
                              data:
                                entity_id: light.kg_keller_light_long
                          - if:
                              condition:
                                binary_sensor.is_on: kg_keller_light_long
                              then:
                                - homeassistant.action:
                                    # The "new" state is not yet propagated
                                    action: light.turn_off
                                    data:
                                      entity_id: light.kg_keller_light_big
                              else:
                                - homeassistant.action:
                                    action: light.turn_on
                                    data:
                                      entity_id: light.kg_keller_light_big

                    - label:
                        text: "Keller Lights"
                        styles: main_controls_label
                        long_mode: DOT

              - obj: !include
                  file: "snippets/lights.yaml"
                  vars:
                    name: "office"
                    label: "Office Light"
                    ha_action: "light.toggle"
                    ha_entity: "light.kg_office_light"

              - obj: !include
                  file: "snippets/lights.yaml"
                  vars:
                    name: "dach"
                    label: "Dach Light"
                    ha_action: "switch.toggle"
                    ha_entity: "switch.dg_studio_light_wall_switch"
