# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Alex Popescu (@pspsalex)

substitutions:
  device_name: "cyd"
  friendly_name: "CYD"

packages:
  base: !include config/base.yaml
  device: !include config/device/cyd.yaml
  theme: !include config/lvgl/themes/grayscale.yaml
  weather: !include config/weather.yaml
  wifi: !include config/wifi.yaml

  boot_screen: !include config/lvgl/pages/boot_screen.yaml
  status_bar: !include config/lvgl/pages/status_bar.yaml
  main_page: !include config/lvgl/pages/main_page.yaml
# Ideas:
# Try to show "live" picture from doorbell camera
# Add icon when someone rang the door but door wasnt opened
# Add list of events to review who rang the camera
