# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alex Popescu (@pspsalex)

# TODO: remove color for lower / raise blinds
# TODO: Fix Dach image
# TODO: check driver - too many artifacts with current update strategy
# TODO: check refresh strategy in driver as when only the clock updates it flickers every 20s - skip refresh if only clock updates? Requires inhibit calls for refresh from yaml to driver
# TODO: Hidden pages cause flickering / screen refresh. Check if this can be prevented somehow?

substitutions:
  device_name: "m5paper"
  friendly_name: "M5Paper"

packages:
  base: !include config/base.yaml
  device: !include config/device/m5paper.yaml
  theme: !include config/lvgl/themes/grayscale/theme.yaml
  weather: !include config/weather.yaml
  wifi: !include config/wifi.yaml

  boot_screen: !include config/lvgl/pages/boot_screen.yaml
  status_bar: !include
    file: config/lvgl/pages/status_bar.yaml
    vars:
      lvgl_status_bar_x: 0
      lvgl_status_bar_y: 0
  main_page: !include config/lvgl/pages/main_page.yaml
