# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Alex Popescu (@pspsalex)

substitutions:
  device_name: "m5paper-qemu"
  friendly_name: "M5Paper (QEMU)"

packages:
  base: !include config/base.yaml
  device: !include config/device/m5paper.yaml
  theme: !include config/lvgl/themes/grayscale.yaml
  weather: !include config/weather.yaml
  # wifi: !include config/wifi.yaml

  boot_screen: !include config/lvgl/pages/boot_screen.yaml
  status_bar: !include config/lvgl/pages/status_bar.yaml
  main_page: !include config/lvgl/pages/main_page.yaml

ethernet:
  type: OPENETH
  manual_ip:
    static_ip: 192.168.48.2
    gateway: 192.168.48.1
    subnet: 255.255.255.0
