# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Alex Popescu (@pspsalex)

substitutions:
  device_name: "sdlcyd"
  friendly_name: "SDLCYD"
  display_width: "800"
  display_height: "480"

packages:
  base: !include config/base.yaml
  device: !include config/device/host.yaml
  theme: !include config/lvgl/themes/dark/theme.yaml
  weather: !include config/weather.yaml

  boot_screen: !include config/lvgl/pages/boot_screen.yaml
  status_bar: !include
    file: config/lvgl/pages/status_bar.yaml
    vars:
      lvgl_status_bar_x: -25
      lvgl_status_bar_y: 20

  # main_page: !include config/lvgl/pages/doorbell.yaml
  main_page: !include
    file: config/lvgl/pages/main_page_cyd.yaml
    vars:
      solar_generation_offset: 545
