# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Alex Popescu (@pspsalex)

substitutions:
  device_name: "sdl"
  friendly_name: "SDL"

packages:
  base: !include config/base.yaml
  device: !include config/device/host.yaml
  theme: !include config/lvgl/themes/grayscale.yaml
  weather: !include config/weather.yaml

  boot_screen: !include config/lvgl/pages/boot_screen.yaml
  status_bar: !include config/lvgl/pages/status_bar.yaml
  main_page: !include config/lvgl/pages/main_page.yaml
