# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Alex Popescu (@pspsalex)

packages:
  icons: !include
    file: ../icons.yaml
    vars:
      theme: default

lvgl:
  style_definitions:
    - id: header_footer

    - id: clean_obj
      border_width: 0
      pad_all: 0
      radius: 0
      outline_width: 0
      shadow_width: 0

    - id: main_controls_button
      # border_width: 0
      # pad_all: 0
      # radius: 0
      # outline_width: 0
      # shadow_width: 0

    - id: main_controls_button_pressed
      # border_width: 0
      # pad_all: 0
      # radius: 0
      # outline_width: 1
      # shadow_width: 0

    - id: main_controls_button_focused
      # border_width: 0
      # pad_all: 0
      # radius: 0
      # outline_width: 0
      # shadow_width: 0

    - id: main_controls_button_checked
      # bg_color: 0x666666

    - id: main_controls
      # border_width: 2
      # border_opa: COVER
      # border_color: 0xcccccc
      # radius: 5
      # pad_all: 5
      # width: 145
      # height: 145

    - id: main_controls_label
      # width: 130
      # height: 40
      # border_width: 4
      # border_color: 0xcccccc
      # border_opa: COVER
      # border_side: TOP
      # text_font: "roboto_24"
      # text_align: center
