# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Alex Popescu (@pspsalex)

packages:
  logger: !include logger.yaml
  ha: !include ha.yaml
  fonts: !include fonts.yaml
  time: !include time.yaml
  lvgl: !include lvgl/lvgl.yaml
