# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Alex Popescu (@pspsalex)

# Enable logging
logger:
  level: DEBUG

  logs:
    lvgl: INFO
    i2c.idf: INFO
    touchscreen: INFO
    # api.connection: VERY_VERBOSE
    # time: VERY_VERBOSE
