/**
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2025 Alex Popescu (@pspsalex)
 *
 * This file was generated by Gemini Flash 3.5 and fixed by Sonnet 5
 */

#pragma once


#include "esphome/core/component.h"
#include "esphome/core/log.h"
#include "esphome/core/automation.h"
#include "esphome/components/lvgl/lvgl_esphome.h"
#include "esphome/components/network/util.h"
#include <esp_http_client.h>
#include <driver/jpeg_decode.h>  // ESP32-P4 HW JPEG Decoder API
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <atomic>
#include <cstring>
#include <string>

namespace esphome {
namespace mjpeg_stream {

static const char *const TAG = "mjpeg_stream";

class MJPEGStreamComponent : public Component {
 public:
  void set_url(const std::string &url) { this->url_ = url; }
  void set_canvas(lv_obj_t *canvas) { this->canvas_ = canvas; }
  void set_dimensions(uint16_t w, uint16_t h) {
    this->width_ = w;
    this->height_ = h;
  }

  // Called from automation actions (or a lambda) to start/stop the stream.
  // Safe to call from the main thread; the background task polls this flag.
  void start_streaming() {
    if (this->streaming_.exchange(true, std::memory_order_relaxed)) {
      return;  // already streaming
    }
    ESP_LOGD(TAG, "Starting MJPEG stream");
  }

  void stop_streaming() {
    if (!this->streaming_.exchange(false, std::memory_order_relaxed)) {
      return;  // already stopped
    }
    ESP_LOGD(TAG, "Stopping MJPEG stream");
  }

  bool is_streaming() const { return this->streaming_.load(std::memory_order_relaxed); }

  void setup() override {
    if (this->canvas_ == nullptr) {
      ESP_LOGE(TAG, "No canvas configured");
      this->mark_failed();
      return;
    }

    // 1. Allocate ping-pong framebuffers (RGB565 = width * height * 2 bytes).
    // These are used directly as the JPEG decoder's output buffer, so they
    // must come from jpeg_alloc_decoder_mem() -- the HW decoder requires the
    // output buffer's address and size to be cache-line aligned, which plain
    // heap_caps_malloc() does not guarantee (this is what caused
    // "decode_outbuf or out_buffer size is not aligned").
    this->fb_size_ = this->width_ * this->height_ * 2;
    jpeg_decode_memory_alloc_cfg_t out_mem_cfg = {
        .buffer_direction = JPEG_DEC_ALLOC_OUTPUT_BUFFER,
    };
    size_t allocated_a = 0, allocated_b = 0;
    this->buf_a_ = (uint8_t *) jpeg_alloc_decoder_mem(this->fb_size_, &out_mem_cfg, &allocated_a);
    this->buf_b_ = (uint8_t *) jpeg_alloc_decoder_mem(this->fb_size_, &out_mem_cfg, &allocated_b);
    if (this->buf_a_ == nullptr || this->buf_b_ == nullptr) {
      ESP_LOGE(TAG, "Failed to allocate %u-byte JPEG decoder output buffers", (unsigned) this->fb_size_);
      this->mark_failed();
      return;
    }
    memset(this->buf_a_, 0, this->fb_size_);
    memset(this->buf_b_, 0, this->fb_size_);
    this->active_buf_.store(this->buf_a_, std::memory_order_relaxed);

    // Point the canvas at the zeroed buffer right away, so it's blank
    // (black) from boot instead of showing whatever garbage was already
    // in the canvas's own memory until the first frame decodes.
    lv_canvas_set_buffer(this->canvas_, this->buf_a_, this->width_, this->height_, LV_COLOR_FORMAT_RGB565);
    lv_obj_invalidate(this->canvas_);

    // Fixed-capacity scratch buffer for assembling one JPEG frame at a time,
    // allocated once from PSRAM. Using a bounded buffer here (instead of a
    // std::vector that reallocates/grows from internal RAM as bytes arrive)
    // means a corrupted or desynced stream can never grow memory usage
    // without limit and crash the device with std::bad_alloc -- if a frame
    // exceeds this cap without hitting an EOI marker, it's treated as lost
    // sync and dropped instead.
    this->jpeg_scratch_ = (uint8_t *) heap_caps_malloc(MAX_JPEG_FRAME_BYTES, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (this->jpeg_scratch_ == nullptr) {
      ESP_LOGE(TAG, "Failed to allocate %u-byte JPEG scratch buffer", (unsigned) MAX_JPEG_FRAME_BYTES);
      this->mark_failed();
      return;
    }

    // 2. Initialize ESP32-P4 hardware JPEG decoder engine
    jpeg_decode_engine_cfg_t decode_eng_cfg = {
        .intr_priority = 0,
        .timeout_ms = 40,
    };
    esp_err_t err = jpeg_new_decoder_engine(&decode_eng_cfg, &this->jpeg_decoder_);
    if (err != ESP_OK) {
      ESP_LOGE(TAG, "Failed to init JPEG decoder engine: %s", esp_err_to_name(err));
      this->mark_failed();
      return;
    }

    // 3. Spawn background streaming task on core 1
    xTaskCreatePinnedToCore(&MJPEGStreamComponent::stream_task_wrapper, "mjpeg_task", 8192, this, 5,
                             &this->task_handle_, 1);
  }

  void loop() override {
    // Check if a new frame is ready to render on the main thread.
    // acquire pairs with the release store in decode_jpeg_frame() so the
    // buffer contents written by the background task are visible here.
    if (this->new_frame_ready_.load(std::memory_order_acquire)) {
      this->new_frame_ready_.store(false, std::memory_order_relaxed);
      uint8_t *buf = this->active_buf_.load(std::memory_order_acquire);
      lv_canvas_set_buffer(this->canvas_, buf, this->width_, this->height_, LV_COLOR_FORMAT_RGB565);
      lv_obj_invalidate(this->canvas_);
    }
  }

 private:
  // Sanity cap for a single JPEG frame. Real frames at typical stream
  // resolutions/quality are well under this; it only exists to bound
  // memory use if the stream loses sync (see connect_and_stream_()).
  static constexpr size_t MAX_JPEG_FRAME_BYTES = 200 * 1024;

  static void stream_task_wrapper(void *pvParameters) {
    auto *self = static_cast<MJPEGStreamComponent *>(pvParameters);
    self->stream_worker();
    vTaskDelete(NULL);
  }

  // Runs forever, idling until start_streaming() is called, and
  // reconnecting after any drop instead of dying permanently.
  void stream_worker() {
    while (true) {
      if (!this->streaming_.load(std::memory_order_relaxed)) {
        vTaskDelay(pdMS_TO_TICKS(200));
        continue;
      }

      // Don't attempt DNS resolution / HTTP connect until the network
      // stack (Wi-Fi/Ethernet + IP) is actually up, or this crashes on
      // boot / after any reconnect.
      if (!network::is_connected()) {
        vTaskDelay(pdMS_TO_TICKS(500));
        continue;
      }

      if (!this->connect_and_stream_()) {
        ESP_LOGW(TAG, "MJPEG stream ended/failed, retrying in 2s");
      }
      vTaskDelay(pdMS_TO_TICKS(2000));
    }
  }

  bool connect_and_stream_() {
    esp_http_client_config_t config = {};
    config.url = this->url_.c_str();
    config.timeout_ms = 5000;

    esp_http_client_handle_t client = esp_http_client_init(&config);
    if (client == nullptr) {
      ESP_LOGE(TAG, "Failed to init HTTP client");
      return false;
    }

    if (esp_http_client_open(client, 0) != ESP_OK) {
      ESP_LOGE(TAG, "Failed to open connection to %s", this->url_.c_str());
      esp_http_client_cleanup(client);
      return false;
    }

    if (esp_http_client_fetch_headers(client) < 0) {
      ESP_LOGE(TAG, "Failed to fetch HTTP headers");
      esp_http_client_cleanup(client);
      return false;
    }

    size_t jpeg_len = 0;
    bool in_frame = false;
    uint8_t prev_byte = 0;
    uint8_t read_buf[2048];

    while (true) {
      if (!this->streaming_.load(std::memory_order_relaxed)) {
        ESP_LOGD(TAG, "Stop requested, closing stream connection");
        break;
      }

      int len = esp_http_client_read(client, (char *) read_buf, sizeof(read_buf));
      if (len <= 0)
        break;

      for (int i = 0; i < len; i++) {
        uint8_t byte = read_buf[i];

        if (!in_frame) {
          // Discard multipart boundary/header bytes until we see a JPEG
          // SOI marker (0xFF 0xD8), which starts the next frame.
          if (prev_byte == 0xFF && byte == 0xD8) {
            in_frame = true;
            jpeg_len = 0;
            this->jpeg_scratch_[jpeg_len++] = 0xFF;
            this->jpeg_scratch_[jpeg_len++] = 0xD8;
          }
          prev_byte = byte;
          continue;
        }

        if (jpeg_len >= MAX_JPEG_FRAME_BYTES) {
          // Never seen an EOI within a sane frame size -- the stream is
          // desynced (dropped/corrupted bytes). Drop what we have and go
          // back to hunting for the next SOI, rather than growing forever.
          ESP_LOGW(TAG, "JPEG frame exceeded %u bytes without an EOI marker, resyncing",
                   (unsigned) MAX_JPEG_FRAME_BYTES);
          in_frame = false;
          prev_byte = byte;
          continue;
        }

        this->jpeg_scratch_[jpeg_len++] = byte;

        // JPEG EOI marker (0xFF 0xD9) ends the frame.
        if (prev_byte == 0xFF && byte == 0xD9) {
          this->decode_jpeg_frame(this->jpeg_scratch_, jpeg_len);
          in_frame = false;
        }
        prev_byte = byte;
      }
    }

    esp_http_client_cleanup(client);
    return true;
  }

  void decode_jpeg_frame(const uint8_t *jpeg_data, size_t jpeg_size) {
    uint8_t *current = this->active_buf_.load(std::memory_order_relaxed);
    uint8_t *target_buf = (current == this->buf_a_) ? this->buf_b_ : this->buf_a_;

    jpeg_decode_cfg_t decode_cfg = {
        .output_format = JPEG_DECODE_OUT_FORMAT_RGB565,
        .rgb_order = JPEG_DEC_RGB_ELEMENT_ORDER_BGR,
    };

    uint32_t out_size = 0;
    esp_err_t ret = jpeg_decoder_process(this->jpeg_decoder_, &decode_cfg, jpeg_data, jpeg_size, target_buf,
                                          this->fb_size_, &out_size);

    if (ret == ESP_OK) {
      // Publish the buffer pointer before the "ready" flag (release), so the
      // consumer's acquire load in loop() is guaranteed to see the finished
      // buffer contents, not a stale/partial one.
      this->active_buf_.store(target_buf, std::memory_order_release);
      this->new_frame_ready_.store(true, std::memory_order_release);
    } else {
      ESP_LOGW(TAG, "JPEG decode failed: %s", esp_err_to_name(ret));
    }
  }

  std::string url_;
  lv_obj_t *canvas_{nullptr};
  uint16_t width_{800};
  uint16_t height_{480};

  uint8_t *buf_a_{nullptr};
  uint8_t *buf_b_{nullptr};
  size_t fb_size_{0};
  uint8_t *jpeg_scratch_{nullptr};
  std::atomic<uint8_t *> active_buf_{nullptr};

  std::atomic<bool> new_frame_ready_{false};
  std::atomic<bool> streaming_{false};
  TaskHandle_t task_handle_{nullptr};
  jpeg_decoder_handle_t jpeg_decoder_{nullptr};
};

template<typename... Ts> class StartAction : public Action<Ts...> {
 public:
  explicit StartAction(MJPEGStreamComponent *parent) : parent_(parent) {}
  void play(Ts... x) override { this->parent_->start_streaming(); }

 protected:
  MJPEGStreamComponent *parent_;
};

template<typename... Ts> class StopAction : public Action<Ts...> {
 public:
  explicit StopAction(MJPEGStreamComponent *parent) : parent_(parent) {}
  void play(Ts... x) override { this->parent_->stop_streaming(); }

 protected:
  MJPEGStreamComponent *parent_;
};

}  // namespace mjpeg_stream
}  // namespace esphome
